<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Abstractions\**" />
    <EmbeddedResource Remove="Abstractions\**" />
    <None Remove="Abstractions\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BugTrackingSystem.Domain\BugTrackingSystem.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Bugs\" />
    <Folder Include="DTOs\" />
  </ItemGroup>

</Project>
